### ISSUE TITLE
BO - Erreur ajout suite à suppression groupée

### ISSUE THREAD

**Issue by jrmvii** [Joeyjoejoe/clients-interface#3]
Après avoir fait un "batch edit" pour supprimer d'un coup l'ensemble des fichiers d'une catégorie, l'interface me propose directement de crééer une fiche dans cette catégorie. Hors à la sauvegarde de ce nouveau élément, après avoir rentré le titre et le fichier j'arrive sur le message d'erreur 
<img width="1767" alt="screen shot 2015-07-24 at 09 00 36" src="https://cloud.githubusercontent.com/assets/6697494/8869427/c6c9b838-31e3-11e5-89a7-847731a028b0.png">
Le bug disparait ensuite, lorsque l'on recommence l'opération, cela fonctionne

**Comment by Joeyjoejoe** [comment]
J'ai supprimé la fonctionnalité de "batch delete" qui pose problème. Cette fonctionnalité n'est pas utile vu le nombre de fiches methodes utilisées par chantiers (3 à 5 max actuellement). Je la retravaillerais si il y a besoin plus tard, pour d'autres activités.
